version: '3'

services:
  broadcast:
    container_name: rtmp
    build: ./rtmp/
    ports:
      - 8080:8080
      - 1935:1935
    tty: true
    command: bash -c "/usr/local/nginx/sbin/nginx && /bin/bash"
